### PR TITLE
change ownership of repos charts to it-sre@mozilla.com

### PR DESCRIPTION
**Pull request by cmharlow**
Jira: Came up in context of pastebin & mozmoderator helm charts

What this PR does:
* changes maintainers to just say Web SRE team & include the it-sre@mozilla.com email.

### CODE REVIEW

**Review by sciurus — DISMISSED** [review]

**Review by bkochendorfer — APPROVED** [review]

**Review by duallain — APPROVED** [review]

**Comment by duallain** [comment]
CI is failing, error is basically that we didn't bump the version of all the charts. I'd vote for merging anyway, as it is today.  But if you wanted to bump all these versions that'd be OK by me as well.  Whichever path seems easiest to you.

```
 ✖︎ configmapsecrets => (version: "0.0.1", path: "charts/configmapsecrets") > Chart version not ok. Needs a version bump!
 ✖︎ ctms => (version: "0.0.16", path: "charts/ctms") > Chart version not ok. Needs a version bump!
 ✖︎ data-alert-sender => (version: "0.0.3", path: "charts/data-alert-sender") > Chart version not ok. Needs a version bump!
 ✖︎ fluentd-papertrail => (version: "0.2.0", path: "charts/fluentd-papertrail") > Chart version not ok. Needs a version bump!
 ✖︎ mozalert-controller => (version: "0.4.0", path: "charts/mozalert-controller") > Chart version not ok. Needs a version bump!
 ✖︎ mozilla-common-voice => (version: "0.4.3", path: "charts/mozilla-common-voice") > Chart version not ok. Needs a version bump!
 ✖︎ mozmoderator => (version: "0.2.0", path: "charts/mozmoderator") > Chart version not ok. Needs a version bump!
 ✖︎ pastebin => (version: "0.1.1", path: "charts/pastebin") > Chart version not ok. Needs a version bump!
 ✖︎ prometheus-customizations => (version: "0.0.2", path: "charts/prometheus-customizations") > Chart version not ok. Needs a version bump!
 ✖︎ refractr => (version: "1.0.25", path: "charts/refractr") > Chart version not ok. Needs a version bump!
 ✖︎ sentence-collector => (version: "0.1.1", path: "charts/sentence-collector") > Chart version not ok. Needs a version bump!
```

**Comment by cmharlow** [comment]
@duallain i'll update it so CI passes in a bit. thanks for sharing that info

**Comment by cmharlow** [comment]
pushing up minor version updates due to maintainer changes. Watching for other CI errors, since i'm guessing a few of these charts haven't been run through CI in a while.

**Comment by cmharlow** [comment]
For refractr Role & RoleBinding update: rbac.authorization.k8s.io/v1

**Comment by cmharlow** [comment]
closing & reopening PR to try to get Travis running again.

**Review by duallain — APPROVED** [review]

**Pull request closed without merging**
