### PR TITLE
Remove cert manager dep

### PR DESCRIPTION
**Pull request by limed**

### CODE REVIEW

**Comment by limed** [comment]
Removed this as this is installed via terraform, we should think hard and fast where it should go (I think terraform makes sense as part of the cluster initialize)

But we are not consistent if we take this path since we are using `HelmRelease` for `ingress-nginx`

**Comment by The-smooth-operator** [comment]
I'm onboard with the idea of installing cert-manager via Terraform, and not from this chart. It is the case now

However I think is good having here cert-manager as a dependency. Because it's needed for local testing, as well as if someone outside from our group wants one day to try refractr.
As you can see [here](https://github.com/mozilla-it/helm-charts/blob/main/charts/refractr/values.yaml#L68-L69) we don't install it by default. Only locally on CI (check values on CI folder).
Regardless of that, if removing it, you should have to remove the dependency too in the [chart definition](https://github.com/mozilla-it/helm-charts/blob/main/charts/refractr/Chart.yaml#L21-L25)

**Review by The-smooth-operator — CHANGES_REQUESTED** [review]
"not agreed with the change"

**Comment by limed** [comment]
Ok i'm ok with leaving this then

**Pull request closed without merging**
