### PR TITLE
Change various .allizom.com to .allizom.org

### PR DESCRIPTION
**Pull request by floatingatoll**
This brings the charts into alignment with DNS, where we have allizom.org but not com. I suspect this is ultimately a no-op, but since I was in the vicinity, submitting for consideration.

### CODE REVIEW

**Comment by cmharlow** [comment]
lets rebase and retry CI on #126 once that's in

**Comment by floatingatoll** [comment]
Rebased onto #126 as it is right now, will update once 126 merges.

**Comment by floatingatoll** [comment]
Even after rebase, it fails, probably because I sourced this PR from a different account. I will leave it in failed state and wait for guidance — happy to resubmit with a local branch if that's best.

**Comment by cmharlow** [comment]
resolving conflicts and running locally to pass CI then merging.

**Review by cmharlow — APPROVED** [review]

**Pull request merged**
